// <auto-generated />
using Labb3MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Labb3MVC.Migrations
{
    [DbContext(typeof(Labb3MVCContext))]
    partial class Labb3MVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb3MVC.Models.Filmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Biljetter");

                    b.Property<string>("Namn");

                    b.Property<int?>("SalongId");

                    b.Property<string>("ShowTime");

                    b.HasKey("Id");

                    b.HasIndex("SalongId");

                    b.ToTable("Filmer");
                });

            modelBuilder.Entity("Labb3MVC.Models.Salong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MaxKapacitet");

                    b.HasKey("Id");

                    b.ToTable("Salong");
                });

            modelBuilder.Entity("Labb3MVC.Models.Filmer", b =>
                {
                    b.HasOne("Labb3MVC.Models.Salong", "Salong")
                        .WithMany("Filmers")
                        .HasForeignKey("SalongId");
                });
#pragma warning restore 612, 618
        }
    }
}
